### ISSUE TITLE
RSSwift does not work in Xcode 6.3 or 6.4 beta

### ISSUE THREAD

**Issue by pbassey** [arled/RSSwift#3]
After resolving all compilation issues caused by the new version of Xcode, I did get the application to compile, but no data displays. It shows the correct number of rows from the xml feed, but no actual text is being retrieved from the xmlparser.

**Comment by arled** [comment]
@pbassey Aware of this issue update coming soon.

**Comment by arled** [comment]
Fixed for Xcode 6 Version 6.3 (6D570)
